---
- name: Create template
  block:
    - name: Create disk for template vm
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}_os_disk_creation"
        size: "{{ vm_template_created_template_disk_size }}"
        storage_domain: "{{ storage_domain_name }}"
      register: _vm_template_created_template_disk

    - name: Create vm
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}"
        cd_iso: "{{ vm_template_created_iso_disk_name }}"
        cluster: "{{ vm_template_created_cluster }}"
        cpu_cores: "{{ vm_template_created_template_cpu_cores_installation }}"
        memory: "{{ vm_template_created_template_memory_installation }}"
        disk_format: cow
        disks:
          - id: "{{ _vm_template_created_template_disk.id }}"
            bootable: true
          - name: "{{ vm_template_created_kickstart_ovirt_disk_name }}"
        storage_domain: "{{ storage_domain_name }}"
        operating_system: "{{ vm_template_created_operating_system_vm_label }}"
        state: present
      register: _vm_template_created_template_vm

    - name: Create nic for the vm_template_created
      ovirt.ovirt.ovirt_nic:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}_nic_1"
        network: "{{ vm_template_created_template_nic_network }}"
        vm: "{{ vm_template_created_template_name }}"

    - name: Start os installation
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}"
        state: running

    - name: Wait for the vm to finish installation
      ovirt.ovirt.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: "name={{ vm_template_created_template_name }} and cluster={{ vm_template_created_cluster }}"
      register: _template_vm_query
      retries: "{{ vm_template_created_template_creation_timeout * 2 }}" # number of retries equals time*2, because retries are made every 0.5 min
      delay: 30
      until: _template_vm_query.ovirt_vms[0].status == "down"

    - name: Detach kickstart disk from template vm
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        state: detached
        vm_name: "{{ vm_template_created_template_name }}"
        name: "{{ vm_template_created_kickstart_ovirt_disk_name }}"

    - name: Remove nic from vm
      ovirt.ovirt.ovirt_nic:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}_nic_1"
        vm: "{{ vm_template_created_template_name }}"
        state: absent

    - name: Change amount of resources assigned to vm
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}"
        cpu_cores: "{{ vm_template_created_template_cpu_cores }}"
        memory: "{{ vm_template_created_template_memory }}"
        memory_guaranteed: "{{ vm_template_created_template_memory }}"
        # get number from variable, multiply by 4 and attach the unit
        memory_max: >-
          {{
            (vm_template_created_template_memory | regex_search('^\d+')) | int * 4 ~
            (vm_template_created_template_memory | regex_search('[a-zA-Z]+$'))
          }}

    - name: Change template disk name
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}_os_disk"
        id: "{{ _vm_template_created_template_disk.id }}"

    - name: Change vm to template
      ovirt.ovirt.ovirt_template:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_template_created_template_name }}"
        vm: "{{ vm_template_created_template_name }}"

  always:
    - name: Detach kickstart disk from template vm
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        state: detached
        vm_name: "{{ vm_template_created_template_name }}"
        name: "{{ vm_template_created_kickstart_ovirt_disk_name }}"
      ignore_errors: true
      # noqa ignore-errors

    # ignore errors in case the machine was not even created
    - name: Remove vm
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: absent
        id: "{{ _vm_template_created_template_vm.id }}"
      ignore_errors: true
    # noqa ignore-errors
