---
- name: Get the key using api
  ansible.builtin.uri:
    url: "https://{{ hosts_prepared_engine }}/ovirt-engine/services/pki-resource?format=OPENSSH-PUBKEY&resource=engine-certificate"
    method: GET
    return_content: true
    validate_certs: false
  register: api_result

- name: Register public ssh key
  ansible.builtin.set_fact:
    engine_public_ssh_key: "{{ api_result.content }}"
