---
- name: Enable ovirt repositories
  hosts: ovirt_machines
  gather_facts: false
  roles:
    - ovirt_repository_installed

- name: Install engine
  hosts: engine
  roles:
    - engine_running

- name: Prepare hosts
  gather_facts: false
  hosts: ovirt_nodes
  roles:
    - hosts_prepared

- name: Add hosts, setup networking and storage, upload default iso
  hosts: engine
  vars:
    upload_default_iso_checksum_location: "{{ default_iso_checksum_location }}"
    upload_default_iso_name: "{{ default_iso_name }}"
    # upload_default_iso_checksum: "{{ default_iso_checksum }}"
    upload_default_iso_location: "{{ default_iso_location }}"
    vm_template_created_iso_disk_name: "{{ default_iso_name }}"
    vm_template_created_template_nic_network: "{{ vm_networks[0].name }}"
  roles:
    - hosts_added
    - networking_setup
    - setup_storage
    - upload_default_iso
    - keycloak_configured
    - vm_template_created
