---
- name: Enable ovirt repositories
  hosts: ovirt_machines
  gather_facts: false
  roles:
    - ovirt_repository_installed

- name: Install engine
  hosts: engine
  roles:
    - engine_running

- name: Prepare hosts
  gather_facts: false
  hosts: ovirt_nodes
  roles:
    - hosts_prepared

- name: Setup first cluster
  hosts: engine
  vars:
    setup_cluster_cpu_type: AMD EPYC
    setup_cluster_cluster_name: cluster_1
  roles:
    - setup_cluster

- name: Setup first cluster
  hosts: engine
  vars:
    setup_cluster_cpu_type: Secure AMD EPYC
    setup_cluster_cluster_name: cluster_2
  roles:
    - setup_cluster


- name: Add nodes to first cluster
  hosts: engine
  vars:
    hosts_added_hosts: "{{ groups['cluster_1'] }}"
    hosts_added_cluster: cluster_1
  roles:
    - hosts_added

- name: Add nodes to second cluster
  hosts: engine
  vars:
    hosts_added_hosts: "{{ groups['cluster_2'] }}"
    hosts_added_cluster: cluster_2
  roles:
    - hosts_added

- name: First cluster networking setup
  hosts: engine
  vars:
    networking_setup_hosts: "{{ groups['cluster_1'] }}"
    networking_setup_cluster: cluster_1
  roles:
    - networking_setup

- name: Second cluster networking setup
  hosts: engine
  vars:
    networking_setup_hosts: "{{ groups['cluster_2'] }}"
    networking_setup_cluster: cluster_2
  roles:
    - networking_setup

- name: Setup storage, upload default iso
  hosts: engine
  vars:
    upload_default_iso_checksum_location: "{{ default_iso_checksum_location }}"
    upload_default_iso_name: "{{ default_iso_name }}"
    upload_default_iso_location: "{{ default_iso_location }}"
    vm_template_created_iso_disk_name: "{{ default_iso_name }}"
    vm_template_created_template_nic_network: "{{ vm_networks[0].name }}"
    vm_template_created_cluster: cluster_1
    keycloak_configured_include_test_data: true
    keycloak_configured_eduvirt_client_id: eduVirt
    vm_template_created_template_creation_timeout: 45
  roles:
    - setup_storage
    - upload_default_iso
    - keycloak_configured
    - vm_template_created

- name: Create test data in first cluster
  hosts: engine
  vars:
    vm_test_data_cluster: cluster_1
  roles:
    - vm_test_data

- name: Create test data in second cluster
  hosts: engine
  vars:
    vm_test_data_cluster: cluster_2
  roles:
    - vm_test_data

- name: Deploy eduVirt
  hosts: engine
  vars_files:
    - vars/passwords.yaml
  roles:
    - deploy_eduvirt
  vars:
    deploy_eduvirt_keycloak_client_secret: "{{ _keycloak_configured_eduvirt_client_secret.clientsecret_info.value }}"
    deploy_eduvirt_mail_host: stud.ics.p.lodz.pl
    deploy_eduvirt_mail_username: vtest-mailer
    # deploy_eduvirt_mail_password:
    # deploy_eduvirt_eduvirt_db_password:
    # deploy_eduvirt_liquibase_password:
    # deploy_eduvirt_jws_secret:
    deploy_ovirt_frontend_image_tag: 0.0.1-dev4
    deploy_ovirt_backend_image_tag: 0.0.1-dev6
    # deploy_ovirt_default_db_password:
    deploy_ovirt_get_certificate: true
