---
- name: Test
  hosts: engine
  vars_files:
    - vars/passwords.yaml
  roles:
    - deploy_eduvirt
  vars:
    deploy_eduvirt_keycloak_client_secret: "{{ _keycloak_configured_eduvirt_client_secret.clientsecret_info.value }}"
    deploy_eduvirt_mail_host: stud.ics.p.lodz.pl
    deploy_eduvirt_mail_username: vtest-mailer
    # deploy_eduvirt_mail_password:
    # deploy_eduvirt_eduvirt_db_password:
    # deploy_eduvirt_liquibase_password:
    # deploy_eduvirt_jws_secret:
    deploy_ovirt_frontend_image_tag: 0.0.1-dev2
    deploy_ovirt_backend_image_tag: 0.0.1-dev3
    # deploy_ovirt_default_db_password:
    deploy_ovirt_get_certificate: true
