---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal

dependencies:
  system:
    - gcc
    - python3.12-devel
    - openssh-clients
  python_interpreter:
    package_system: python3.12 
    python_path: "/usr/bin/python3.12"
  ansible_core:
    package_pip: ansible-core==2.18.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  galaxy: galaxy-requirements.yaml
  python: python-requirements.txt

options:
  package_manager_path: /usr/bin/dnf-3
