- name: Download image checksum
  ansible.builtin.get_url:
    url: "{{ upload_default_iso_checksum_location }}"
    dest: "{{ upload_default_iso_working_dir }}/{{ upload_default_iso_name }}-CHECKSUM"
    mode: '0400'
  register: _upload_default_iso_downloaded_checksum
  when: upload_default_iso_checksum is undefined

- name: Save checksum to file
  ansible.builtin.copy:
    content: "{{ upload_default_iso_checksum }}"
    dest: "{{ upload_default_iso_working_dir }}/{{ upload_default_iso_name }}.iso-CHECKSUM"
    mode: '0400'
  register: _upload_default_iso_bare_checksum
  when: upload_default_iso_checksum is defined


- name: Extract iso name from url
  ansible.builtin.set_fact:
    _upload_default_iso_filename: "{{ upload_default_iso_location | regex_replace('.*/', '') }}"

# Suppress failure of the stage regardless of the return of checksum check
- name: Check existing iso checksum
  ansible.builtin.command: >
    sha256sum -c {{ (_upload_default_iso_downloaded_checksum.dest is defined) |
     ternary(_upload_default_iso_downloaded_checksum.dest, _upload_default_iso_bare_checksum.dest) }}
  register: _upload_default_iso_checksum_result
  changed_when: false
  failed_when: false

- name: Download default image
  ansible.builtin.get_url:
    url: "{{ upload_default_iso_location }}"
    dest: "{{ upload_default_iso_working_dir }}/{{ _upload_default_iso_filename }}"
    mode: '0400'
  when: _upload_default_iso_filename in _upload_default_iso_checksum_result.stderr
