---
- name: Setup cluster
  block:
    - name: Authorize to engine
      ovirt.ovirt.ovirt_auth:
        url: https://{{ ansible_host }}/ovirt-engine/api
        insecure: true
        username: "{{ ovirt_admin_username }}"
        password: "{{ ovirt_admin_password }}"
        state: present

    - name: Create first cluster
      ovirt.ovirt.ovirt_cluster:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ setup_cluster_datacenter }}"
        name: "{{ setup_cluster_cluster_name }}"
        cpu_type: "{{ setup_cluster_cpu_type }}"
        compatibility_version: "{{ setup_cluster_compability_version }}"
        fence_enabled: false

  always:
    - name: Always revoke the SSO token
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
