argument_specs:
  main:
    short_description: Role for adding nodes to engine.
    description:
      - Role for adding nodes to engine.
      - Adds nodes to the engine running on the specified host.
      - Requires variables ovirt_admin_username and ovirt_admin_password, used for authentication to ovirt, to be set for host.
    author: Jakub Kozielski
    options:
      hosts_added_cluster:
        type: str
        default: Default
        description: Cluster to which add the nodes.

      hosts_added_hosts:
        type: list
        required: true
        description:
          - Hosts from the inventory to be added to the engine.
          - Use group['name_of_the_group']
