argument_specs:
  main:
    short_description: Role for configuring the networking of nodes.
    description:
      - Role for configuring the networking of nodes.
      - Configures management network by removing vm traffic, adds storage network to the node and trunkated network for vm's usage.
      - >
        Nodes are taken from the specified inventory group. Each of the hosts has to have
        [mgmt_mac], [storage_mac], [trunk_mac] specified, which represent respective network interface mac addresses.
      - >
        Additionaly a [storage_ip] and [vm_networks] is needed, [storage_ip] for each of the nodes,
        which represent ip address which should be assigned to the storage interface.
        [vm_networks] for the execution host, a list of pairs of [name]: a string with the name of the name of the network
        and [vlan_tag]: number representing a vlan tag assigned to the network.

      - Requires variables ovirt_admin_username and ovirt_admin_password, used for authentication to ovirt, to be set for host.
    author: Jakub Kozielski
    options:
      networking_setup_cluster:
        type: str
        default: Default
        description: Cluster where the nodes are located.

      networking_setup_data_center:
        type: str
        default: Default
        description: Data center where the networks should be created.

      networking_setup_hosts:
        type: list
        required: true
        description:
          - Hosts from the inventory to be added to the engine.
          - Use group['name_of_the_group']
