ovirt_machines:
  children:
    ovirt_engine:
    ovirt_nodes:

ovirt_engine:
  hosts:
    engine:
      ansible_host: vteste3.vlab.it.p.lodz.pl

ovirt_nodes:
  hosts:
    node1:
      ansible_host: vtesth31.vlab.it.p.lodz.pl
    node2:
      ansible_host: vtesth32.vlab.it.p.lodz.pl
