- name: Retrieve access token from Keycloak
  ansible.builtin.uri:
    url: "{{ keycloak_configured_keycloak_url }}/realms/{{ keycloak_configured_keycloak_realm }}/protocol/openid-connect/token"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    body:
      client_id: "{{ keycloak_configured_client_id }}"
      # client_secret: "{{ keycloak_configured_client_secret }}"
      username: "{{ keycloak_configured_keycloak_admin_user }}"
      password: "{{ keycloak_configured_keycloak_admin_password }}"
      grant_type: password
      # scope: openid
    body_format: form-urlencoded
    return_content: true
    validate_certs: "{{ keycloak_configured_validate_certs }}"
  register: _keycloak_configured_keycloak_response

- name: Register keycloak token
  ansible.builtin.set_fact:
    _keycloak_configured_token: "{{ (_keycloak_configured_keycloak_response.content | from_json).access_token }}"
