---
- name: Login into Keycloak
  ansible.builtin.include_tasks: login.ansible.yaml

- name: Create eduVirt client
  community.general.keycloak_client:
    auth_keycloak_url: "{{ keycloak_configured_keycloak_url }}"
    token: "{{ _keycloak_configured_token }}"
    state: present
    redirect_uris: "{{ keycloak_configured_redirect_uris }}"
    realm: "{{ keycloak_configured_realm }}"
    client_id: "{{ keycloak_configured_eduvirt_client_id }}"
    public_client: false
    validate_certs: "{{ keycloak_configured_validate_certs }}"
    attributes:
      access.token.lifespan: 900
      client.session.idle.timeout: 5400
    protocol_mappers:
      - config:
          access.token.claim: true
          claim.name: groups
          full.path: true
          id.token.claim: true
          userinfo.token.claim: true
        consentRequired: false
        name: groups
        protocol: openid-connect
        protocolMapper: oidc-group-membership-mapper

- name: Retrieve client secret
  community.general.keycloak_clientsecret_info:
    auth_keycloak_url: "{{ keycloak_configured_keycloak_url }}"
    token: "{{ _keycloak_configured_token }}"
    realm: "{{ keycloak_configured_realm }}"
    validate_certs: "{{ keycloak_configured_validate_certs }}"
    client_id: "{{ keycloak_configured_eduvirt_client_id }}"
  register: _keycloak_configured_eduvirt_client_secret

- name: Create groups for eduVirt
  community.general.keycloak_group:
    auth_keycloak_url: "{{ keycloak_configured_keycloak_url }}"
    token: "{{ _keycloak_configured_token }}"
    realm: "{{ keycloak_configured_realm }}"
    validate_certs: "{{ keycloak_configured_validate_certs }}"
    name: "{{ item }}"
  with_items: "{{ _keycloak_configured_eduvirt_groups }}"

- name: Add Keycloak Users
  loop: "{{ keycloak_configured_users }}"
  ansible.builtin.include_tasks: add_user.ansible.yaml
  when: keycloak_configured_include_test_data
