- name: Authorize and add storage
  block:
    - name: Authorize to engine
      ovirt.ovirt.ovirt_auth:
        url: https://{{ ansible_host }}/ovirt-engine/api
        insecure: true
        username: "{{ ovirt_admin_username }}"
        password: "{{ ovirt_admin_password }}"
        state: present

    - name: Add storage domain
      ovirt.ovirt.ovirt_storage_domain:
        state: present
        host: "{{ setup_storage_connecting_host }}"
        data_center: "{{ setup_storage_data_center }}"
        name: "{{ storage_domain_name }}"
        nfs:
          address: "{{ setup_storage_address }}"
          path: "{{ storage_path }}"
        auth: "{{ ovirt_auth }}"

  always:
    - name: Always revoke the SSO token
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
